services:
  - type: web
    name: jungae-validator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: BUILDING_HUB_KEY
        sync: false
      - key: VWORLD_KEY
        sync: false
      - key: VWORLD_DOMAIN
        value: jungae-validator.onrender.com
